# Generated by Django 5.0.6 on 2024-06-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educaWeb', '0002_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='titulo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
