# Generated by Django 5.0.6 on 2024-07-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educaWeb', '0003_leccion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
