# Generated by Django 5.0.6 on 2024-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educaWeb', '0004_alter_leccion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
